- icon: "icon ion-coffee"
  title: "Branding"
  content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut"

- icon: "icon ion-compass"
  title: "Web Design"
  content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut"  